import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useReducer,
} from "react";
import { getPsbtVersionNumber, PsbtV2 } from "@caravan/psbt";
import { Network } from "@caravan/bitcoin";
import { getEncoding } from "../functions";

const getPsbtFromUrlHash = (): string | null => {
  const hash = window.location.hash.slice(1);
  if (!hash) {
    return null;
  }
  const params = new URLSearchParams(hash);
  const psbt = params.get("psbt");
  return psbt ? decodeURIComponent(psbt) : null;
};

const buildUrlHashWithPsbt = (psbt: string): string => {
  return `#psbt=${encodeURIComponent(psbt)}`;
};

// Helper to get the display serialization (matches what's shown in Psbt component)
const getDisplaySerialization = (
  currentPsbt: string,
  encoding: "hex" | "base64" | null,
  serializeAsV0: "true" | "false",
): string => {
  if (!currentPsbt) {
    return "";
  }

  const version = getPsbtVersionNumber(currentPsbt);
  const psbt =
    version === 2 ? new PsbtV2(currentPsbt, true) : PsbtV2.FromV0(currentPsbt, true);

  if (serializeAsV0 === "false") {
    return psbt.serialize(encoding || undefined);
  } else {
    return psbt.toV0(encoding || undefined);
  }
};

interface IPageState {
  encoding: "hex" | "base64" | null;
  network: Exclude<Network, Network.SIGNET>;
  serializeAsV0: "true" | "false";
  currentPsbt: string;
  // Current position in browser history stack (increments on push, changes on back/forward)
  historyDepth: number;
  // Highest depth reached (resets when new PSBT is pushed, stays same on back/forward)
  maxHistoryDepth: number;
}

export interface IPageContext extends IPageState {
  setState: (state: Partial<IPageState>) => void;
}

const stateReducer = (
  oldState: IPageState,
  newState: Partial<IPageState>,
): IPageState => {
  return {
    ...oldState,
    ...newState,
  };
};

const getInitialState = (): IPageState => {
  const urlPsbt = getPsbtFromUrlHash();
  if (urlPsbt) {
    try {
      // Validate the PSBT from hash
      const version = getPsbtVersionNumber(urlPsbt);
      if (version === 2) {
        new PsbtV2(urlPsbt, true);
      } else {
        PsbtV2.FromV0(urlPsbt, true);
      }
      return {
        encoding: getEncoding(urlPsbt),
        network: Network.TESTNET,
        serializeAsV0: "false",
        currentPsbt: urlPsbt,
        historyDepth: 0,
        maxHistoryDepth: 0,
      };
    } catch (e) {
      console.error("Invalid PSBT in URL hash:", e);
    }
  }
  // Default: empty PSBT, no hash in URL
  return {
    encoding: "base64",
    network: Network.TESTNET,
    serializeAsV0: "false",
    currentPsbt: new PsbtV2().serialize(),
    historyDepth: 0,
    maxHistoryDepth: 0,
  };
};

const defaultState: IPageState = getInitialState();

export const PageContext = createContext<IPageContext>({
  ...defaultState,
  setState: () => {},
});

// Sync URL hash when serializeAsV0 changes
const useUrlHashSync = ({currentPsbt, serializeAsV0, historyDepth}: IPageState) => {
  useEffect(() => {
    // Skip if we're at the initial empty state with no URL hash
    if (historyDepth === 0 && !window.location.hash) {
      return;
    }

    // Compute what the hash should be (always base64 for URL)
    const displayPsbt = getDisplaySerialization(
      currentPsbt,
      "base64",
      serializeAsV0,
    );
    if (!displayPsbt) return;

    const expectedHash = buildUrlHashWithPsbt(displayPsbt);

    // Only update if different from current URL (avoids double-update after pushState)
    if (window.location.hash !== expectedHash) {
      window.history.replaceState(
        { depth: historyDepth },
        "",
        expectedHash,
      );
    }
  }, [currentPsbt, serializeAsV0, historyDepth]);
};

// Listen for browser back/forward navigation
const usePopStateListener = (
  setState: (state: Partial<IPageState>) => void,
) => {
  useEffect(() => {
    const handlePopState = (event: PopStateEvent) => {
      const urlPsbt = getPsbtFromUrlHash();
      const depth = event.state?.depth ?? 0;

      if (urlPsbt) {
        try {
          // Validate the PSBT
          const version = getPsbtVersionNumber(urlPsbt);
          if (version === 2) {
            new PsbtV2(urlPsbt, true);
          } else {
            PsbtV2.FromV0(urlPsbt, true);
          }
          setState({
            currentPsbt: urlPsbt,
            // Should always be base64 for URL hash as long as the hash was generated by this app
            encoding: getEncoding(urlPsbt),
            historyDepth: depth,
          });
        } catch (e) {
          console.error("Invalid PSBT in URL hash:", e);
        }
      } else {
        // No URL hash means we're at an empty state. Initialize with an empty PSBT.
        setState({
          currentPsbt: new PsbtV2().serialize(),
          encoding: "base64",
          historyDepth: 0,
        });
      }
    };

    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, [setState]);
};

export const withContext = <P extends object>(
  WrappedComponent: React.ComponentType<P>,
) => {
  const ComponentWithContext = (props: P) => {
    const [state, setState] = useReducer(stateReducer, defaultState);
    const context = useMemo<IPageContext>(
      () => ({
        ...state,
        setState,
      }),
      [state],
    );
    usePopStateListener(setState);
    useUrlHashSync(state);

    return (
      <PageContext.Provider value={context}>
        <WrappedComponent {...props} />
      </PageContext.Provider>
    );
  };

  return ComponentWithContext;
};

export const useUpdatePsbt = () => {
  const { setState, encoding, historyDepth, serializeAsV0 } = useContext(PageContext);

  const updatePsbt = useCallback(
    (psbt: PsbtV2 | string) => {
      let serialized: string;
      let newEncoding = encoding;

      // This validates the psbt
      if (typeof psbt === "string") {
        newEncoding = getEncoding(psbt);
        const version = getPsbtVersionNumber(psbt);
        if (version === 2) {
          new PsbtV2(psbt, true);
        } else {
          PsbtV2.FromV0(psbt, true);
        }
        // Store original string (preserves v0 indicator)
        serialized = psbt;
      } else {
        new PsbtV2(psbt.serialize(), true);
        serialized = psbt.serialize();
      }

      const newDepth = historyDepth + 1;

      // Push to browser history with display serialization (always base64 for URL)
      const displayPsbt = getDisplaySerialization(serialized, "base64", serializeAsV0);
      const hash = buildUrlHashWithPsbt(displayPsbt);
      window.history.pushState({ depth: newDepth }, "", hash);

      // Update React state (maxHistoryDepth resets to newDepth since forward history is cleared)
      setState({
        currentPsbt: serialized,
        encoding: newEncoding,
        historyDepth: newDepth,
        maxHistoryDepth: newDepth,
      });
    },
    [setState, historyDepth, encoding, serializeAsV0],
  );

  return updatePsbt;
};

export const usePsbt = () => {
  const { currentPsbt } = useContext(PageContext);
  const version = useCurrentPsbtVersion();

  if (!currentPsbt) {
    return new PsbtV2();
  }

  if (version === 2) {
    return new PsbtV2(currentPsbt, true);
  } else {
    return PsbtV2.FromV0(currentPsbt, true);
  }
};

export const usePopHistory = () => {
  return useCallback(() => {
    window.history.back();
  }, []);
};

export const usePushHistory = () => {
  return useCallback(() => {
    window.history.forward();
  }, []);
};

export const useCurrentPsbtVersion = () => {
  const { currentPsbt } = useContext(PageContext);
  return useMemo(() => getPsbtVersionNumber(currentPsbt || ""), [currentPsbt]);
};

export const useSerializedPsbt = () => {
  const { currentPsbt, encoding, serializeAsV0 } = useContext(PageContext);
  return useMemo(
    () => getDisplaySerialization(currentPsbt, encoding, serializeAsV0),
    [currentPsbt, encoding, serializeAsV0],
  );
};